
project_id = "teicwhbrboudzrjvtarg"

[api]
enabled = true

[db]
shadow_database_url = ""

[auth]
enabled = true

[storage]
enabled = true

[realtime]
enabled = false

[functions]
[functions.create-booking]
verify_jwt = true
