// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://teicwhbrboudzrjvtarg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlaWN3aGJyYm91ZHpyanZ0YXJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTk5NTcsImV4cCI6MjA2MDk3NTk1N30.WvPJQ3MAmRF8Y9EH_m9BMD7Iq2NoRpcL8ykP3RCZN_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);